# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1443, 904)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Delphi/proj3 — release/icon2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.toolBox = QtWidgets.QToolBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.toolBox.setFont(font)
        self.toolBox.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.toolBox.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.toolBox.setObjectName("toolBox")
        self.widget = QtWidgets.QWidget()
        self.widget.setGeometry(QtCore.QRect(0, 0, 1421, 708))
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.groupBox_3 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_3.setMaximumSize(QtCore.QSize(450, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.treeView = QtWidgets.QTreeView(self.groupBox_3)
        self.treeView.setMaximumSize(QtCore.QSize(440, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.treeView.setFont(font)
        self.treeView.setStyleSheet("border: none; background: transparent;")
        self.treeView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.treeView.setObjectName("treeView")
        self.treeView.header().setVisible(False)
        self.verticalLayout_2.addWidget(self.treeView)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_13.addWidget(self.pushButton_7)
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_13.addWidget(self.pushButton_8)
        self.horizontalLayout_12.addWidget(self.groupBox_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_11.addWidget(self.groupBox_3)
        self.tabWidget = QtWidgets.QTabWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setStyleSheet("font: 9pt \"Century Gothic\";")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.East)
        self.tabWidget.setElideMode(QtCore.Qt.ElideLeft)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_7)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableView = QtWidgets.QTableView(self.tab_7)
        self.tableView.setStyleSheet("border:none; ")
        self.tableView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableView.setAutoScroll(False)
        self.tableView.setAlternatingRowColors(False)
        self.tableView.setObjectName("tableView")
        self.verticalLayout_3.addWidget(self.tableView)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_7)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_10.addWidget(self.pushButton)
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_10.addWidget(self.pushButton_3)
        self.horizontalLayout_6.addWidget(self.groupBox_2)
        self.groupBox = QtWidgets.QGroupBox(self.tab_7)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_3.addWidget(self.comboBox)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_3.addWidget(self.pushButton_2)
        self.horizontalLayout_6.addWidget(self.groupBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.tabWidget.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_8)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tableView_3 = QtWidgets.QTableView(self.tab_8)
        self.tableView_3.setStyleSheet("border: none;")
        self.tableView_3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableView_3.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableView_3.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableView_3.setObjectName("tableView_3")
        self.verticalLayout_4.addWidget(self.tableView_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_2.setSpacing(1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab_8)
        self.groupBox_8.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_8.setObjectName("groupBox_8")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_8)
        self.horizontalLayout_4.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.groupBox_9 = QtWidgets.QGroupBox(self.groupBox_8)
        self.groupBox_9.setObjectName("groupBox_9")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox_9)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.comboBox_4 = QtWidgets.QComboBox(self.groupBox_9)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.verticalLayout_9.addWidget(self.comboBox_4)
        self.horizontalLayout_4.addWidget(self.groupBox_9)
        self.groupBox_10 = QtWidgets.QGroupBox(self.groupBox_8)
        self.groupBox_10.setObjectName("groupBox_10")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.groupBox_10)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.comboBox_5 = QtWidgets.QComboBox(self.groupBox_10)
        self.comboBox_5.setObjectName("comboBox_5")
        self.verticalLayout_10.addWidget(self.comboBox_5)
        self.horizontalLayout_4.addWidget(self.groupBox_10)
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_8)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_6.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_6.setContentsMargins(-1, 0, -1, 1)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.comboBox_7 = QtWidgets.QComboBox(self.groupBox_5)
        self.comboBox_7.setObjectName("comboBox_7")
        self.verticalLayout_6.addWidget(self.comboBox_7)
        self.comboBox_6 = QtWidgets.QComboBox(self.groupBox_5)
        self.comboBox_6.setObjectName("comboBox_6")
        self.verticalLayout_6.addWidget(self.comboBox_6)
        self.horizontalLayout_4.addWidget(self.groupBox_5)
        self.groupBox_11 = QtWidgets.QGroupBox(self.groupBox_8)
        self.groupBox_11.setObjectName("groupBox_11")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.groupBox_11)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.dateEdit = QtWidgets.QDateEdit(self.groupBox_11)
        self.dateEdit.setCalendarPopup(False)
        self.dateEdit.setCurrentSectionIndex(0)
        self.dateEdit.setTimeSpec(QtCore.Qt.LocalTime)
        self.dateEdit.setObjectName("dateEdit")
        self.verticalLayout_11.addWidget(self.dateEdit)
        self.horizontalLayout_4.addWidget(self.groupBox_11)
        self.horizontalLayout_2.addWidget(self.groupBox_8)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.pushButton_11 = QtWidgets.QPushButton(self.tab_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_11.sizePolicy().hasHeightForWidth())
        self.pushButton_11.setSizePolicy(sizePolicy)
        self.pushButton_11.setObjectName("pushButton_11")
        self.verticalLayout_16.addWidget(self.pushButton_11)
        self.pushButton_16 = QtWidgets.QPushButton(self.tab_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_16.sizePolicy().hasHeightForWidth())
        self.pushButton_16.setSizePolicy(sizePolicy)
        self.pushButton_16.setObjectName("pushButton_16")
        self.verticalLayout_16.addWidget(self.pushButton_16)
        self.horizontalLayout_2.addLayout(self.verticalLayout_16)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.groupBox_18 = QtWidgets.QGroupBox(self.tab_8)
        self.groupBox_18.setCheckable(True)
        self.groupBox_18.setChecked(False)
        self.groupBox_18.setObjectName("groupBox_18")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_18)
        self.verticalLayout_5.setContentsMargins(-1, 4, -1, 5)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.spinBox = QtWidgets.QSpinBox(self.groupBox_18)
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(20)
        self.spinBox.setProperty("value", 1)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout_21.addWidget(self.spinBox)
        self.verticalLayout_5.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_18.addWidget(self.groupBox_18)
        self.verticalLayout_8.addLayout(self.horizontalLayout_18)
        self.pushButton_12 = QtWidgets.QPushButton(self.tab_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_12.sizePolicy().hasHeightForWidth())
        self.pushButton_12.setSizePolicy(sizePolicy)
        self.pushButton_12.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_12.setObjectName("pushButton_12")
        self.verticalLayout_8.addWidget(self.pushButton_12)
        self.horizontalLayout_2.addLayout(self.verticalLayout_8)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.tabWidget.addTab(self.tab_8, "")
        self.horizontalLayout_11.addWidget(self.tabWidget)
        self.toolBox.addItem(self.widget, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 1421, 708))
        self.page_2.setObjectName("page_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox_7 = QtWidgets.QGroupBox(self.page_2)
        self.groupBox_7.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_7.setFont(font)
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.listView = QtWidgets.QListView(self.groupBox_7)
        self.listView.setStyleSheet("border: none;\n"
"background: transparent;")
        self.listView.setObjectName("listView")
        self.verticalLayout_7.addWidget(self.listView)
        self.groupBox_15 = QtWidgets.QGroupBox(self.groupBox_7)
        self.groupBox_15.setObjectName("groupBox_15")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.groupBox_15)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.pushButton_10 = QtWidgets.QPushButton(self.groupBox_15)
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_14.addWidget(self.pushButton_10)
        self.pushButton_9 = QtWidgets.QPushButton(self.groupBox_15)
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_14.addWidget(self.pushButton_9)
        self.verticalLayout_7.addWidget(self.groupBox_15)
        self.gridLayout_2.addWidget(self.groupBox_7, 0, 0, 2, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(self.page_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableView_2 = QtWidgets.QTableView(self.groupBox_6)
        self.tableView_2.setStyleSheet("border: none;\n"
"background: white;")
        self.tableView_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableView_2.setAutoScroll(False)
        self.tableView_2.setObjectName("tableView_2")
        self.tableView_2.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.tableView_2)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.groupBox_16 = QtWidgets.QGroupBox(self.groupBox_6)
        self.groupBox_16.setObjectName("groupBox_16")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.groupBox_16)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_16)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_15.addWidget(self.pushButton_5)
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_16)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_15.addWidget(self.pushButton_6)
        self.horizontalLayout_9.addWidget(self.groupBox_16)
        self.groupBox_17 = QtWidgets.QGroupBox(self.groupBox_6)
        self.groupBox_17.setObjectName("groupBox_17")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.groupBox_17)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_17)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_16.addWidget(self.pushButton_4)
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox_17)
        self.comboBox_2.setObjectName("comboBox_2")
        self.horizontalLayout_16.addWidget(self.comboBox_2)
        self.horizontalLayout_9.addWidget(self.groupBox_17)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.comboBox_3 = QtWidgets.QComboBox(self.groupBox_6)
        self.comboBox_3.setObjectName("comboBox_3")
        self.verticalLayout.addWidget(self.comboBox_3)
        self.gridLayout_2.addWidget(self.groupBox_6, 0, 1, 2, 1)
        self.toolBox.addItem(self.page_2, "")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 1421, 708))
        self.page.setObjectName("page")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.tableView_4 = QtWidgets.QTableView(self.page)
        self.tableView_4.setEnabled(True)
        self.tableView_4.setStyleSheet("border:none; ")
        self.tableView_4.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableView_4.setAutoScroll(False)
        self.tableView_4.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableView_4.setAlternatingRowColors(False)
        self.tableView_4.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableView_4.setObjectName("tableView_4")
        self.tableView_4.horizontalHeader().setDefaultSectionSize(173)
        self.tableView_4.verticalHeader().setVisible(False)
        self.horizontalLayout_8.addWidget(self.tableView_4)
        self.tableView_5 = QtWidgets.QTableView(self.page)
        self.tableView_5.setStyleSheet("border:none; ")
        self.tableView_5.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableView_5.setAutoScroll(False)
        self.tableView_5.setAlternatingRowColors(True)
        self.tableView_5.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableView_5.setObjectName("tableView_5")
        self.tableView_5.verticalHeader().setVisible(False)
        self.horizontalLayout_8.addWidget(self.tableView_5)
        self.verticalLayout_13.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.groupBox_13 = QtWidgets.QGroupBox(self.page)
        self.groupBox_13.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_13.setFont(font)
        self.groupBox_13.setObjectName("groupBox_13")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.groupBox_13)
        self.verticalLayout_12.setContentsMargins(-1, 1, -1, 1)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.pushButton_15 = QtWidgets.QPushButton(self.groupBox_13)
        self.pushButton_15.setObjectName("pushButton_15")
        self.verticalLayout_12.addWidget(self.pushButton_15)
        self.checkBox = QtWidgets.QCheckBox(self.groupBox_13)
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_12.addWidget(self.checkBox)
        self.horizontalLayout_5.addWidget(self.groupBox_13)
        self.groupBox_14 = QtWidgets.QGroupBox(self.page)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_14.setFont(font)
        self.groupBox_14.setObjectName("groupBox_14")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_14)
        self.horizontalLayout.setContentsMargins(-1, 1, -1, 1)
        self.horizontalLayout.setSpacing(4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comboBox_8 = QtWidgets.QComboBox(self.groupBox_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_8.sizePolicy().hasHeightForWidth())
        self.comboBox_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.comboBox_8.setFont(font)
        self.comboBox_8.setObjectName("comboBox_8")
        self.horizontalLayout.addWidget(self.comboBox_8)
        self.comboBox_10 = QtWidgets.QComboBox(self.groupBox_14)
        self.comboBox_10.setMaximumSize(QtCore.QSize(100, 16777215))
        self.comboBox_10.setObjectName("comboBox_10")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_10)
        self.comboBox_9 = QtWidgets.QComboBox(self.groupBox_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_9.sizePolicy().hasHeightForWidth())
        self.comboBox_9.setSizePolicy(sizePolicy)
        self.comboBox_9.setMaximumSize(QtCore.QSize(100, 16777215))
        self.comboBox_9.setObjectName("comboBox_9")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_9)
        self.pushButton_13 = QtWidgets.QPushButton(self.groupBox_14)
        self.pushButton_13.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_13.setObjectName("pushButton_13")
        self.horizontalLayout.addWidget(self.pushButton_13)
        self.horizontalLayout_5.addWidget(self.groupBox_14)
        self.pushButton_14 = QtWidgets.QPushButton(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_14.sizePolicy().hasHeightForWidth())
        self.pushButton_14.setSizePolicy(sizePolicy)
        self.pushButton_14.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_14.setFont(font)
        self.pushButton_14.setObjectName("pushButton_14")
        self.horizontalLayout_5.addWidget(self.pushButton_14)
        self.verticalLayout_13.addLayout(self.horizontalLayout_5)
        self.toolBox.addItem(self.page, "")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 1421, 708))
        self.page_3.setObjectName("page_3")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label = QtWidgets.QLabel(self.page_3)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setText("")
        self.label.setObjectName("label")
        self.verticalLayout_15.addWidget(self.label)
        self.toolBox.addItem(self.page_3, "")
        self.verticalLayout_14.addWidget(self.toolBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1443, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.action_5 = QtWidgets.QAction(MainWindow)
        self.action_5.setObjectName("action_5")
        self.action_6 = QtWidgets.QAction(MainWindow)
        self.action_6.setObjectName("action_6")
        self.action_7 = QtWidgets.QAction(MainWindow)
        self.action_7.setObjectName("action_7")
        self.action_8 = QtWidgets.QAction(MainWindow)
        self.action_8.setObjectName("action_8")
        self.menu.addAction(self.action_8)
        self.menu.addAction(self.action)
        self.menu.addAction(self.action_7)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(0)
        self.toolBox.layout().setSpacing(7)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ИС \"Деканат\""))
        self.groupBox_4.setTitle(_translate("MainWindow", "Действия"))
        self.pushButton_7.setText(_translate("MainWindow", "Добавить"))
        self.pushButton_8.setText(_translate("MainWindow", "Удалить"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Действия:"))
        self.pushButton.setText(_translate("MainWindow", "Добавить"))
        self.pushButton_3.setText(_translate("MainWindow", "Удалить"))
        self.groupBox.setTitle(_translate("MainWindow", "Изменить группу"))
        self.pushButton_2.setText(_translate("MainWindow", "Применить"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("MainWindow", "Студенты"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Новая"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Вид"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "Контрольная работа"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "Зачёт"))
        self.comboBox_4.setItemText(2, _translate("MainWindow", "Экзамен"))
        self.comboBox_4.setItemText(3, _translate("MainWindow", "Курсовая работа"))
        self.comboBox_4.setItemText(4, _translate("MainWindow", "Курсовой проект"))
        self.groupBox_10.setTitle(_translate("MainWindow", "Дисциплина"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Преподаватель"))
        self.groupBox_11.setTitle(_translate("MainWindow", "Дата"))
        self.dateEdit.setDisplayFormat(_translate("MainWindow", "dd-MM-yyyy"))
        self.pushButton_11.setText(_translate("MainWindow", "Добавить"))
        self.pushButton_16.setText(_translate("MainWindow", "Печать статистики"))
        self.groupBox_18.setTitle(_translate("MainWindow", "Выбор семестра"))
        self.pushButton_12.setText(_translate("MainWindow", "Удалить запись"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), _translate("MainWindow", "Проверочные работы"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.widget), _translate("MainWindow", "Студенты и проверочные работы"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Кафедра"))
        self.groupBox_15.setTitle(_translate("MainWindow", "Действия"))
        self.pushButton_10.setText(_translate("MainWindow", "Добавить"))
        self.pushButton_9.setText(_translate("MainWindow", "Удалить"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Преподаватель"))
        self.groupBox_16.setTitle(_translate("MainWindow", "Действия"))
        self.pushButton_5.setText(_translate("MainWindow", "Добавить"))
        self.pushButton_6.setText(_translate("MainWindow", "Удалить"))
        self.groupBox_17.setTitle(_translate("MainWindow", "Изменить кафедру"))
        self.pushButton_4.setText(_translate("MainWindow", "Применить"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("MainWindow", "Преподаватели"))
        self.groupBox_13.setTitle(_translate("MainWindow", "Печать выписки"))
        self.pushButton_15.setText(_translate("MainWindow", "Приступить к печати"))
        self.checkBox.setText(_translate("MainWindow", "Добавить средний балл"))
        self.groupBox_14.setTitle(_translate("MainWindow", "Новая запись"))
        self.comboBox_10.setItemText(0, _translate("MainWindow", "Экзамен"))
        self.comboBox_10.setItemText(1, _translate("MainWindow", "Зачёт"))
        self.comboBox_10.setItemText(2, _translate("MainWindow", "Контрольная работа"))
        self.comboBox_10.setItemText(3, _translate("MainWindow", "Курсовая работа"))
        self.comboBox_10.setItemText(4, _translate("MainWindow", "Курсовой проект"))
        self.comboBox_9.setItemText(0, _translate("MainWindow", "Незачёт"))
        self.comboBox_9.setItemText(1, _translate("MainWindow", "Зачёт"))
        self.comboBox_9.setItemText(2, _translate("MainWindow", "Отлично"))
        self.comboBox_9.setItemText(3, _translate("MainWindow", "Хорошо"))
        self.comboBox_9.setItemText(4, _translate("MainWindow", "Удовлетворительно"))
        self.comboBox_9.setItemText(5, _translate("MainWindow", "Неудовлетворительно"))
        self.pushButton_13.setText(_translate("MainWindow", "Добавить"))
        self.pushButton_14.setText(_translate("MainWindow", "Удалить"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("MainWindow", "Ведомости"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), _translate("MainWindow", "Страница"))
        self.menu.setTitle(_translate("MainWindow", "Меню"))
        self.action.setText(_translate("MainWindow", "О разработчике"))
        self.action_2.setText(_translate("MainWindow", "Не о разработчике"))
        self.action_5.setText(_translate("MainWindow", "Ведомостей"))
        self.action_6.setText(_translate("MainWindow", "Процентной статистики"))
        self.action_7.setText(_translate("MainWindow", "Выход"))
        self.action_8.setText(_translate("MainWindow", "Вызов справки"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

